In [1]:
import numpy as np
import gym
import random

env = gym.make("FrozenLake-v0")

action_size = env.action_space.n
state_size = env.observation_space.n

In [2]:


# Feel free to play with these hyperparameters

total_episodes =15000       # Total episodes
test_episodes = 100            # Test episodes
learning_rate = 0.8           # Learning rate
max_steps =  99              # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005            # Exponential decay rate for exploration prob



In [3]:
# Initializations
qtable = np.zeros((state_size, action_size))
rewards = []
print(qtable.shape)

(16, 4)


In [4]:


for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # Choose an action a in the current state (greedy or explore)
        
        # im doing an ephsilon greedy approach
        exp_exp_tradeoff = random.uniform(0, 1)  
        # exploitation (taking the max Q value for this state)
        if exp_exp_tradeoff > epsilon:
            # Enter code here            
            action = np.argmax(qtable[state,:])
            ## Hint: Greedily choose an action according to Q value

        # exploration
        else:
            # Enter code here
            ## Hint: Randomly choose an action
            action = env.action_space.sample()

        # Take this action and observe
        new_state, reward, done, info = env.step(action)

        # Do a Q update
        # Enter code here
        ## Hint: One line update equation convert to one line code, start with "qtable[state, action] = ..."
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        state = new_state
        
        if done == True: 
            break
        
    # Decay epsilon to reduce exploration as time progresses
    
    # Enter code here to assign a decay value to "decay_parameter"
    decay_parameter = np.exp(-decay_rate*episode) 
    ## Hint: 
    ## 1. Use inbuilt polynomial, exponential(, or whatever works) functions to decay epsilon
    ## 2. "decay_parameter" is a function of "decay_rate" and "episode"
    
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*decay_parameter
    rewards.append(total_rewards)

print("Score over time: " +  str(sum(rewards)/total_episodes))
print("Q values:")
print(qtable)

Score over time: 0.502472
Q values:
[[1.06604298e-01 4.89020646e-02 5.55658405e-02 5.58627083e-02]
 [2.09496623e-03 1.14031622e-02 2.36897292e-03 5.93783756e-02]
 [1.30710210e-02 3.70789941e-02 6.51422851e-03 4.77493593e-02]
 [1.56839142e-03 1.31989524e-04 5.77272835e-03 4.81765689e-02]
 [1.34294955e-01 6.35527315e-02 2.43045749e-02 1.15439294e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.03897266e-02 1.88843178e-04 3.96642155e-04 1.97306470e-10]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.42794618e-02 6.16658466e-04 3.55420027e-02 1.08463071e-01]
 [6.35401759e-02 6.37215638e-01 1.39548430e-04 3.07810675e-02]
 [8.80740883e-01 5.59787774e-04 2.08826465e-05 6.66272511e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.74881122e-03 2.72472618e-02 5.63705035e-01 9.63693070e-02]
 [5.93899253e-02 9.95351349e-01 7.39775169e-01 7.92416160e-02]
 [0.00000000e+00 0.

In [6]:


########################################################################
#################### Final policy animation ############################
########################################################################

print("We only print the last state in each episode, to see if our agent has reached the destination or fallen into a hole")
env.reset()
# Total episodes
test_episodes = 100      
for episode in range(test_episodes):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        # Taking action with Q learning
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            env.render()
            
            print("Number of steps", step)
            break
        state = new_state
env.close()



We only print the last state in each episode, to see if our agent has reached the destination or fallen into a hole
****************************************************
('EPISODE ', 0)
  (Down)
SFFF
FHFH
FFFH
HFFG
('Number of steps', 69)
****************************************************
('EPISODE ', 1)
  (Down)
SFFF
FHFH
FFFH
HFFG
('Number of steps', 27)
****************************************************
('EPISODE ', 2)
  (Down)
SFFF
FHFH
FFFH
HFFG
('Number of steps', 54)
****************************************************
('EPISODE ', 3)
  (Down)
SFFF
FHFH
FFFH
HFFG
('Number of steps', 12)
****************************************************
('EPISODE ', 4)
  (Down)
SFFF
FHFH
FFFH
HFFG
('Number of steps', 77)
****************************************************
('EPISODE ', 5)
  (Down)
SFFF
FHFH
FFFH
HFFG
('Number of steps', 45)
****************************************************
('EPISODE ', 6)
  (Up)
SFFF
FHFH
FFFH
HFFG
('Number of steps', 99)
********************************